### ISSUE TITLE
Implementation guidance

### ISSUE THREAD

**Issue by brinsche** [seanchas116/SimpleDALPlugin#1]
Sorry for abusing the issues like this, but I'm interested in adapting this sample to use Android smartphones as macOS webcams, the app [IP Webcam](https://play.google.com/store/apps/details?id=com.pas.webcam&hl=en) allows the device to stream a MJPEG stream of its camera via http://device_ip:port/video  

Could you give me any pointers about what APIs to use to basically just open that stream and reuse it as the input for the plugin? Ideally with minimal input lag, I imagine that could be achieved by using a small buffer for the stream

Thanks in advance!

**Comment by seanchas116** [comment]
I haven't tried yet but maybe replacing [here](https://github.com/seanchas116/SimpleDALPlugin/blob/ea928c31d0cb4224dfd75b5db4887304fd6728b8/SimpleDALPlugin/Stream.swift#L26) with [kCMVideoCodecType_JPEG](https://developer.apple.com/documentation/coremedia/kcmvideocodectype_jpeg) make it possible to send MJPEG as stream.
Then you could create samplebuffer with `CMIOSampleBufferCreate` from raw JPEG from IP webcam instead of `CMIOSampleBufferCreateForImageBuffer`.

**Comment by brinsche** [comment]
Thanks for the help! I'll try from there
